import { generateConstants } from '../../vendors/ew-angularjs-utils/utils/generate-constants';

const domain = 'DASHBOARD';
const custom = {
  GET_CARS_DATA: `${domain}/GET_CARS_DATA`,
  GET_CARS_DATA_FULFILLED: `${domain}/GET_CARS_DATA_FULFILLED`,
  GET_CARS_DATA_PENDING: `${domain}/GET_CARS_DATA_PENDING`,
  GET_CARS_DATA_REJECTED: `${domain}/GET_CARS_DATA_REJECTED`,

  GET_CONTRACTS_DATA: `${domain}/GET_CONTRACTS_DATA`,
  GET_CONTRACTS_DATA_FULFILLED: `${domain}/GET_CONTRACTS_DATA_FULFILLED`,
  GET_CONTRACTS_DATA_PENDING: `${domain}/GET_CONTRACTS_DATA_PENDING`,
  GET_CONTRACTS_DATA_REJECTED: `${domain}/GET_CONTRACTS_DATA_REJECTED`,

  GET_NOTES_DATA: `${domain}/GET_NOTES_DATA`,
  GET_NOTES_DATA_FULFILLED: `${domain}/GET_NOTES_DATA_FULFILLED`,
  GET_NOTES_DATA_PENDING: `${domain}/GET_NOTES_DATA_PENDING`,
  GET_NOTES_DATA_REJECTED: `${domain}/GET_NOTES_DATA_REJECTED`,

  GET_PAYMENTS_DATA: `${domain}/GET_PAYMENTS_DATA`,
  GET_PAYMENTS_DATA_FULFILLED: `${domain}/GET_PAYMENTS_DATA_FULFILLED`,
  GET_PAYMENTS_DATA_PENDING: `${domain}/GET_PAYMENTS_DATA_PENDING`,
  GET_PAYMENTS_DATA_REJECTED: `${domain}/GET_PAYMENTS_DATA_REJECTED`,

  SAVE_NOTES: `${domain}/SAVE_NOTES`,
  SAVE_NOTES_FULFILLED: `${domain}/SAVE_NOTES_FULFILLED`,
  SAVE_NOTES_PENDING: `${domain}/SAVE_NOTES_PENDING`,
  SAVE_NOTES_REJECTED: `${domain}/SAVE_NOTES_REJECTED`,
};
const constants = generateConstants(domain, custom);

export const DASHBOARD = constants;
