import { generateConstants } from '../../vendors/ew-angularjs-utils/utils/generate-constants';

const domain = 'ROOMS';
const custom = {
  GET_DISPONIBILITA: `${domain}/GET_DISPONIBILITA`,
  GET_DISPONIBILITA_FULFILLED: `${domain}/GET_DISPONIBILITA_FULFILLED`,
  GET_DISPONIBILITA_PENDING: `${domain}/GET_DISPONIBILITA_PENDING`,
  GET_DISPONIBILITA_REJECTED: `${domain}/GET_DISPONIBILITA_REJECTED`,
  
  GET_DISPONIBILITA_CAMPO: `${domain}/GET_DISPONIBILITA_CAMPO`,
  GET_DISPONIBILITA_CAMPO_FULFILLED: `${domain}/GET_DISPONIBILITA_CAMPO_FULFILLED`,
  GET_DISPONIBILITA_CAMPO_PENDING: `${domain}/GET_DISPONIBILITA_CAMPO_PENDING`,
  GET_DISPONIBILITA_CAMPO_REJECTED: `${domain}/GET_DISPONIBILITA_CAMPO_REJECTED`,
};
const constants = generateConstants(domain, custom);

export const ROOMS = constants;
